# Generated by Django 6.1 on 2026-08-25 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneModels',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True)),
                ('description', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionStages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(unique=True)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(db_index=True, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'In Progress'), (2, 'Ready'), (3, 'Defective'), (4, 'Shipped')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Drone', to='production.dronemodels')),
            ],
        ),
        migrations.CreateModel(
            name='DroneStageLogs',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('worker_id', models.CharField(default='Worker')),
                ('is_defective', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('drone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DroneStageLogs', to='production.drone')),
                ('stage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DroneStageLogs', to='production.productionstages')),
            ],
        ),
    ]
