# Generated by Django 6.1 on 2026-08-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_drone_id_alter_dronemodels_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='status',
            field=models.IntegerField(choices=[(1, 'In Progress'), (2, 'Ready'), (3, 'Defective'), (4, 'Shipped')], default=1),
        ),
    ]
