# Generated by Django 6.1 on 2026-08-20 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='StockOperation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.IntegerField(choices=[(1, 'In'), (2, 'Out'), (3, 'Write Off')])),
                ('quantity', models.PositiveIntegerField()),
                ('performed_by', models.CharField(default='Admin')),
                ('recipient', models.CharField(default='User')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockoperation', to='warehouse.part')),
            ],
        ),
    ]
